export const VIEW_BREAKPOINTS = {
  MOBILE: 480,
  TABLET: 768,
  DESKTOP: 1024,
  QUAD: 3840,
};

export const STRING_BREAKPOINTS = {
  MOBILE: VIEW_BREAKPOINTS.MOBILE + 'px',
  TABLET: VIEW_BREAKPOINTS.TABLET + 'px',
  DESKTOP: VIEW_BREAKPOINTS.DESKTOP + 'px',
  QUAD: VIEW_BREAKPOINTS.QUAD + 'px',
};
